name: plannera
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  dartz: ^0.10.1
  dio: ^5.9.0
  equatable: ^2.0.7
  firebase_auth: 4.19.6    # 👈 downgrade para compatibilidad con Swift 5
  firebase_core: 2.30.1 
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localization: ^0.3.1
  flutter_secure_storage: ^9.2.4
  get_it: ^8.2.0
  go_router: ^16.1.0
  scrollable_positioned_list: ^0.3.8
  table_calendar: ^3.2.0

dependency_overrides:
  intl: ^0.20.0
  
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
