// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ2g-f4LzIvjB00v8BUAkChxbwiGzESFE',
    appId: '1:516224889397:web:964916a755dea4fbc4b77c',
    messagingSenderId: '516224889397',
    projectId: 'plannera-c4f27',
    authDomain: 'plannera-c4f27.firebaseapp.com',
    storageBucket: 'plannera-c4f27.firebasestorage.app',
    measurementId: 'G-DVPZ358B0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHec9YDGEygPKvYDJ8pjynavrBuNbglRg',
    appId: '1:516224889397:android:b7add8645ce2518ac4b77c',
    messagingSenderId: '516224889397',
    projectId: 'plannera-c4f27',
    storageBucket: 'plannera-c4f27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCVzu89PrDJ5TpvI5TaicJTuTk1-UJjqg',
    appId: '1:516224889397:ios:6d2df9a7c2d758f2c4b77c',
    messagingSenderId: '516224889397',
    projectId: 'plannera-c4f27',
    storageBucket: 'plannera-c4f27.firebasestorage.app',
    iosBundleId: 'com.example.plannera',
  );
}
